### PR TITLE
Container With Most Water

### PR DESCRIPTION
**Pull request by Zaman3027**
https://github.com/dexterpuru/leetcode_python/issues/8

### CODE REVIEW

**Comment by dexterpuru** [comment]
@Zaman3027 good work with the code, please put link of related issue in the PR's description.

**Comment by Zaman3027** [comment]
Done

**Comment by Zaman3027** [comment]
https://github.com/dexterpuru/leetcode_cpp/issues/44
done

**Comment by Zaman3027** [comment]
https://github.com/dexterpuru/leetcode_python/issues/8
Done

**Review by dexterpuru — APPROVED** [review]

**Pull request merged**
